name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: âœ¨ Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: ğŸ› ï¸ Build Solution
        working-directory: ./src/
        run: dotnet build

      - name: ğŸ§ª Test
        working-directory: ./src/
        env:
          CB_SLACK_TOKEN: ${{ secrets.CB_SLACK_TOKEN }}
        run: dotnet test

      - name: ğŸ› ï¸ Build Release
        working-directory: ./src/CbSlackStats.Functions/
        run: dotnet build --configuration Release --no-restore --output ./output

      - name: ğŸš€ Publish
        uses: Azure/functions-action@v1
        with:
          app-name: "CbSlackStatsFunctionApp"
          package: "./src/CbSlackStats.Functions/output"
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
